/**
 * Unit tests for ingestForAgent command handler (Plan 015 Milestone 4)
 * Simplified approach: Test implementation logic directly without command registration
 */

import { expect } from 'chai';
import { validateIngestRequest, generateDefaultMetadata } from '../validation/summaryValidator';
import { CogneeIngestRequest } from '../types/agentIntegration';

suite('Agent Ingestion Command Handler Logic', () => {
    
    suite('Schema Validation', () => {
        test('accepts truly minimal payload (topic + context only)', () => {
            const payload: any = {
                topic: 'Test Topic',
                context: 'Test context'
                // No metadata at all - should be auto-generated by command handler
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.true;
            expect(result.errors).to.be.empty;
        });

        test('accepts valid minimal payload with metadata', () => {
            const payload: CogneeIngestRequest = {
                topic: 'Test Topic',
                context: 'Test context',
                metadata: {
                    topicId: 'test-001',
                    createdAt: '2025-11-19T10:00:00Z',
                    updatedAt: '2025-11-19T10:00:00Z'
                }
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.true;
            expect(result.errors).to.be.empty;
        });

        test('accepts valid full payload with all optional fields', () => {
            const payload: CogneeIngestRequest = {
                topic: 'Full Topic',
                context: 'Full context',
                decisions: ['Decision 1'],
                rationale: ['Rationale 1'],
                openQuestions: ['Question 1'],
                nextSteps: ['Step 1'],
                references: ['Ref 1'],
                timeScope: '2025-11-19T08:00:00Z to 09:00:00Z',
                metadata: {
                    topicId: 'test-full',
                    sessionId: 'session-001',
                    planId: '015',
                    status: 'Active',
                    createdAt: '2025-11-19T10:00:00Z',
                    updatedAt: '2025-11-19T10:00:00Z'
                },
                agentName: 'Test Agent'
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.true;
        });

        test('rejects payload missing topic', () => {
            const payload: any = {
                context: 'Test context',
                metadata: {
                    topicId: 'test-001',
                    createdAt: '2025-11-19T10:00:00Z',
                    updatedAt: '2025-11-19T10:00:00Z'
                }
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.false;
            expect(result.errors.some(e => e.includes('topic'))).to.be.true;
        });

        test('rejects payload missing context', () => {
            const payload: any = {
                topic: 'Test Topic',
                metadata: {
                    topicId: 'test-001',
                    createdAt: '2025-11-19T10:00:00Z',
                    updatedAt: '2025-11-19T10:00:00Z'
                }
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.false;
            expect(result.errors.some(e => e.includes('context'))).to.be.true;
        });

        test('accepts payload with partial metadata (remaining fields auto-generated)', () => {
            const payload: any = {
                topic: 'Test Topic',
                context: 'Test context',
                metadata: {
                    planId: '015'
                    // Missing topicId, createdAt, updatedAt - should be auto-generated
                }
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.true;
            expect(result.errors).to.be.empty;
        });

        test('rejects payload with invalid status enum', () => {
            const payload: any = {
                topic: 'Test Topic',
                context: 'Test context',
                metadata: {
                    topicId: 'test-001',
                    status: 'InvalidStatus',
                    createdAt: '2025-11-19T10:00:00Z',
                    updatedAt: '2025-11-19T10:00:00Z'
                }
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.false;
            expect(result.errors.some(e => e.includes('status'))).to.be.true;
        });

        test('rejects non-array decisions field', () => {
            const payload: any = {
                topic: 'Test Topic',
                context: 'Test context',
                decisions: 'Not an array',
                metadata: {
                    topicId: 'test-001',
                    createdAt: '2025-11-19T10:00:00Z',
                    updatedAt: '2025-11-19T10:00:00Z'
                }
            };

            const result = validateIngestRequest(payload);
            expect(result.valid).to.be.false;
            expect(result.errors.some(e => e.includes('decisions'))).to.be.true;
        });
    });

    suite('Metadata Generation', () => {
        test('generates required metadata fields', () => {
            const metadata = generateDefaultMetadata('test-id');

            expect(metadata.topicId).to.equal('test-id');
            expect(metadata.status).to.equal('Active');
            expect(metadata.createdAt).to.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);
            expect(metadata.updatedAt).to.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/);
        });

        test('allows overriding default values', () => {
            const metadata = generateDefaultMetadata('test-id', {
                status: 'Superseded',
                sessionId: 'session-123'
            });

            expect(metadata.status).to.equal('Superseded');
            expect(metadata.sessionId).to.equal('session-123');
        });
    });

    // Note: Full integration tests that actually call the command are in
    // agentIngestion.integration.test.ts since they require proper
    // workspace setup including extension activation
});
