/**
 * API Contract Types (Synced Copy)
 *
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️
 *
 * This file is automatically synced from the canonical source:
 * /api-contract/types.ts
 *
 * To update, run: npm run sync-contract
 *
 * The canonical api-contract/ remains the single source of truth.
 * This copy exists only to satisfy TypeScript's rootDir constraint.
 */

// Re-export everything from the synced copy
export * from './types';
